num_timesteps: 1e7
num_envs: 1024
num_steps_per_env_per_update: 64
num_epochs: 2
num_minibatches: 2

# PQN BR params
lr: 2.5e-4
start_e: 1.0
end_e: 0.05
exploration_fraction: 0.2
q_lambda: 0.9
max_grad_norm: 0.5

# Shared
gamma: 0.99
fc_dim_size: 128

# NFSP params
anticipatory_eta: 0.1
sl_reservoir_capacity: 100000
sl_batch_size: 256
sl_num_steps_per_update: 2
sl_lr: 3e-4

env_name: hul
seed: 0
num_seeds: 5
env_kwargs:
  num_agents: 2

# comparison
compare: true
compare_mode: checkpoint  # "random" or "checkpoint"
compare_with: ./checkpoints/hul_rebel_2026-03-02_00-41-36.msgpack
compare_network_type: value  # "actor_critic" or "value" (value = REBEL value network)
compare_value_hidden_dim: 128  # hidden dim for REBEL value network (must match checkpoint)
compare_steps: 100
compare_interval: 1

# wandb
project: bluffjax
job_type: hul_pqn_nfsp
wandb: true
